version: '3.8'

services:
  backend:
    build: ./praktikum7_api
    container_name: webgis_backend
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build: ./frontend_sig_123140020
    container_name: webgis_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped